// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/index/hash/{hash}": {
            "post": {
                "description": "Find matching indexed files with a given hash",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Game Data Index"
                ],
                "summary": "Index Hash Search",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Hash to check",
                        "name": "hash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/IndexHashResponse"
                        }
                    }
                }
            }
        },
        "/api/index/path": {
            "post": {
                "description": "Find matching indexed files with a given path prefix",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Game Data Index"
                ],
                "summary": "Index Path Search",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/IndexPathRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/IndexPathResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "GameSlim": {
            "type": "object",
            "properties": {
                "date_added": {
                    "type": "string",
                    "example": "2018-01-12T02:13:56.633Z"
                },
                "id": {
                    "type": "string",
                    "example": "08143aa7-f3ae-45b0-a1d4-afa4ac44c845"
                },
                "platform_name": {
                    "type": "string",
                    "example": "Flash"
                },
                "title": {
                    "type": "string",
                    "example": "Alien Hominid"
                }
            }
        },
        "IndexHashResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/IndexMatch"
                    }
                },
                "games": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/GameSlim"
                    }
                },
                "hash": {
                    "type": "string",
                    "example": "d32d41389d088db60d177d731d83f839"
                },
                "type": {
                    "type": "string",
                    "example": "md5"
                }
            }
        },
        "IndexMatch": {
            "type": "object",
            "properties": {
                "crc32": {
                    "type": "string",
                    "example": "b102ef01"
                },
                "date_added": {
                    "type": "integer",
                    "example": 1704945196068
                },
                "game_id": {
                    "type": "string",
                    "example": "08143aa7-f3ae-45b0-a1d4-afa4ac44c845"
                },
                "md5": {
                    "type": "string",
                    "example": "d32d41389d088db60d177d731d83f839"
                },
                "path": {
                    "type": "string",
                    "example": "content/uploads.ungrounded.net/59000/59593_alien_booya202c.swf"
                },
                "sha1": {
                    "type": "string",
                    "example": "d435e0d0eefe30d437f0df41c926449077cab22e"
                },
                "sha256": {
                    "type": "string",
                    "example": "06c8bf04fd9a3d49fa9e1fe7bb54e4f085aae4163f7f9fbca55c8622bc2a6278"
                },
                "size": {
                    "type": "integer",
                    "example": 2037879
                }
            }
        },
        "IndexPathRequest": {
            "type": "object",
            "properties": {
                "path": {
                    "type": "string"
                }
            }
        },
        "IndexPathResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/IndexMatch"
                    }
                },
                "games": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/GameSlim"
                    }
                },
                "paths": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "content/uploads.ungrounded.net/59000/"
                    ]
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "fpfss.unstable.life",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Flashpoint Submission API",
	Description:      "Yup, it's an API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
